BEGIN
    PKG_FITNESS.EMPTY_TABLES();
--     PKG_FITNESS.FILL_TABLES();
--     PKG_FITNESS.BEWIJS_MILESTONE_5();
--     PKG_FITNESS.PRINTREPORT_2_LEVELS(1, -2, 5);
--     PKG_FITNESS.PRINTREPORT_2_LEVELS(1, 2, 5);
--     PKG_FITNESS.COMPARISON_SINGLE_BULK_M7(20, 40, 700, FALSE);
    PKG_FITNESS.COMPARISON_SINGLE_BULK_M7(20, 40, 700, TRUE);
--     PKG_FITNESS.COMPARISON_SINGLE_BULK_M7(20, 40, 70, FALSE);
--     PKG_FITNESS.COMPARISON_SINGLE_BULK_M7(20,40, 70, TRUE);
    COMMIT;
END;


-- Controle m4
-- SELECT 'fitnesses' AS table_name, (SELECT COUNT(*) FROM FITNESS) AS table_count FROM dual UNION
-- SELECT 'addresses', (SELECT COUNT(*) FROM ADDRESS) FROM dual UNION
-- SELECT 'memberschips', (SELECT COUNT(*) FROM MEMBERCHIPCARDS) FROM dual UNION
-- SELECT 'abonnements', (SELECT COUNT(*) FROM ABONNEMENTS) FROM dual UNION
-- SELECT 'members', (SELECT COUNT(*) FROM MEMBERS) FROM dual UNION
-- SELECT 'machines', (SELECT COUNT(*) FROM MACHINES) FROM dual UNION
-- SELECT 'exercises', (SELECT COUNT(*) FROM EXERCISES) FROM dual UNION
-- SELECT 'difficulty', (SELECT COUNT(*) FROM DIFFICULTYS) FROM dual UNION
-- SELECT 'musclegroups', (SELECT COUNT(*) FROM MUSCLEGROUPS) FROM dual UNION
-- SELECT 'timeofpractices', (SELECT COUNT(*) FROM TIMEOFPRACTICES) FROM dual;


-- Controle m5 stap 2
-- SELECT mcp.MEMBERSCHIPID, mcp.STARTDATE, mcp.ENDDATE, f.NAME, m.NAME, a.NAME
-- FROM MEMBERCHIPCARDS mcp
-- JOIN FITNESS f on f.FITNESSID = mcp.FITNESS_FITNESSID
-- JOIN MEMBERS m on mcp.MEMBER_MEMBERID = m.MEMBERID
-- JOIN ABONNEMENTS a on a.ABONNEMENTID = mcp.ABONNEMENT_ABONNEMENTID
-- ORDER BY MEMBERSCHIPID;

-- Controle m5 stap 3 - m7
-- SELECT * FROM FITNESS;
-- SELECT * FROM MACHINES ORDER BY MACHINEID;
-- SELECT MACHINE_MACHINEID, COUNT(*) FROM EXERCISES GROUP BY MACHINE_MACHINEID ORDER BY MACHINE_MACHINEID;
-- SELECT FITNESS_FITNESSID, COUNT(*) FROM MACHINES GROUP BY FITNESS_FITNESSID ORDER BY FITNESS_FITNESSID;
-- SELECT COUNT(*) FROM EXERCISES;